<header>
			<img src='images/NewLogo.png' alt='Single Page Applications' id='logo' title='Single Page Applications' />
	
			<nav>
				<a href='index.php' class="menu" title="Home">Home</a>&#160;&#160;&#160;
				<a href='topic.php' class="menu" target="_blank" title="Learn more about SPAs">SPAs In Depth</a>&#160;&#160;&#160;
				<a href='enhancements.html' class="menu" target="_blank" title="Check out my enhancements">Enhancements</a>&#160;&#160;&#160;
				<a href='quiz.php' class="menu" target="_blank" title="Take a short quiz">Quiz</a>&#160;&#160;&#160;
				<a href="authenticate.php" class="menu" target="_blank">Manage</a>&#160;&#160;&#160;
				<a href="phpenhancements.php" class="menu" target="_blank">PHP Enhancements</a>
				
			</nav><br />
</header>